## GA Data Science 19 (DAT19) - Class 3 - Python  

### iPython Notebook Magic

#### Short cut keys:

comment out a line of code = command + /

run block of code = shift + enter

autocomplete text = tab

help for function = shift + tab

Web based viewer for ipython notebooks http://nbviewer.ipython.org/
###### Note: GitHub now renders iPython notebooks natively, making looking at labs easy from any computer

In [1]:
print 'Hello World'

Hello World


### Basic python data types:



The most basic data structure, analogous to NULL in other languages

In [2]:
print type(None)

<type 'NoneType'>


There are four numeric types: ***int, float, bool***, and ***complex***.

In [3]:
type(5)

int

In [4]:
type('five')

str

In [5]:
type(2.5)

float

In [6]:
type(True)

bool

In [7]:
type(2+3j)

complex

In [8]:
type(False)

bool

Basic math with basic types - pretty obvious, except watch for integer division!

In [9]:
5 + 5

10

In [10]:
3 * 7

21

In [11]:
x = 10
y = 5
z = 4

In [12]:
x - y

5

In [13]:
x / y

2

In [14]:
x / z  # gives just the integer!

2

In [15]:
x / 4.0  # converts to float division if one operand is a float

2.5

In [16]:
x / float(z)  # equivalent - use float to 'cast' z to a float

2.5

In [17]:
10 % 4  # modulo  operator(i.e. remainder)

2

A better way to handle integer division is to import the future module:

In [18]:
from __future__ import division

In [19]:
print 10/4 #works as you would expect
print 10//4 #integer division can still be specified

2.5
2


The internal difference is that without that import, / is mapped to the `__div__()` method, while with it, `__truediv__()` is used. (In any case, // calls `__floordiv__()`.)

## Non-Numeric Types / Python Data Structures
If you go through the python documentation there are many different types but the important ones we'll cover here. We'll also introduce more complex types throughout the course. Types you'll frequently interact with are:
- strings (which play interestingly with lists, we'll see in a sec)
- lists
- tuples
- sets
- dictionaries

#### Python lists  

The next basic data type is the Python ***list***.
* A list is an ***ordered collection of elements***, and these elements can be of arbitrary type.
* Lists are ***mutable***, meaning they can be changed in-place.
* In python lists are indicated by square brackets **`[`** and **`]`**.
* Items in a list are indexed starting with 0.

In [20]:
new_list = []
print type(new_list)

<type 'list'>


In [21]:
new_list_2 = list()
print type(new_list_2)

<type 'list'>


In [22]:
k = [1, 'b', True]

In [23]:
k[2]

True

In [24]:
k[1] = 'a'

In [25]:
k

[1, 'a', True]

You can even have lists of lists:

In [26]:
a = [[1,2,3], 4, 5]

In [27]:
a[0]

[1, 2, 3]

In [28]:
a[1]

4

Working with lists:

In [29]:
nums = [5, 5.0, 'five']     # multiple data types

In [30]:
print nums

[5, 5.0, 'five']


In [31]:
type(nums)

list

In [32]:
len(nums)

3

How do we get the first element of the list and then replace it?

In [33]:
nums.append(7)   # list 'method' that modifies the list

In [34]:
help(nums.append)

Help on built-in function append:

append(...)
    L.append(object) -- append object to end



In [35]:
help(nums)

Help on list object:

class list(object)
 |  list() -> new empty list
 |  list(iterable) -> new list initialized from iterable's items
 |  
 |  Methods defined here:
 |  
 |  __add__(...)
 |      x.__add__(y) <==> x+y
 |  
 |  __contains__(...)
 |      x.__contains__(y) <==> y in x
 |  
 |  __delitem__(...)
 |      x.__delitem__(y) <==> del x[y]
 |  
 |  __delslice__(...)
 |      x.__delslice__(i, j) <==> del x[i:j]
 |      
 |      Use of negative indices is not supported.
 |  
 |  __eq__(...)
 |      x.__eq__(y) <==> x==y
 |  
 |  __ge__(...)
 |      x.__ge__(y) <==> x>=y
 |  
 |  __getattribute__(...)
 |      x.__getattribute__('name') <==> x.name
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __getslice__(...)
 |      x.__getslice__(i, j) <==> x[i:j]
 |      
 |      Use of negative indices is not supported.
 |  
 |  __gt__(...)
 |      x.__gt__(y) <==> x>y
 |  
 |  __iadd__(...)
 |      x.__iadd__(y) <==> x+=y
 |  
 |  __imul__(...)
 |      x.__imul__(y) <==

In [36]:
nums.remove('five')
print nums

[5, 5.0, 7]


In [37]:
nums[0] = 6    # replace a list element

We can sort the list:

In [38]:
sorted(nums)  # 'function' that does not modify the list

[5.0, 6, 7]

In [39]:
print nums #not affected

[6, 5.0, 7]


In [40]:
nums = sorted(nums) #overwrites our original list
print nums

[5.0, 6, 7]


In [41]:
sorted(nums, reverse=True)  # optional argument reverses sort order

[7, 6, 5.0]

#### List slicing

In [42]:
weekdays = ['mon','tues','wed','thurs','fri']

In [43]:
weekdays[0]         # element 0

'mon'

In [44]:
weekdays[0:3]       # elements 0, 1, 2

['mon', 'tues', 'wed']

In [45]:
weekdays[:3]        # elements 0, 1, 2

['mon', 'tues', 'wed']

In [46]:
weekdays[3:]        # elements 3, 4

['thurs', 'fri']

In [47]:
weekdays[-1]        # last element (element 4)

'fri'

In [48]:
weekdays[::2]       # every 2nd element (0, 2, 4)

['mon', 'wed', 'fri']

In [49]:
weekdays[::-1]      # backwards (4, 3, 2, 1, 0)

['fri', 'thurs', 'wed', 'tues', 'mon']

In [50]:
days = weekdays + ['sat','sun']     # concatenate lists
print days

['mon', 'tues', 'wed', 'thurs', 'fri', 'sat', 'sun']


#### Python Strings
Strings are written with either single or double quotes and have a variety of methods to operate on them. We will not work with much text data early on but as we go deeper into the class, feature creation based off of text data may be useful for your projects. A few useful methods:

In [51]:
a = 'Hello world!'
print a
print a.lower()
print a.upper()

Hello world!
hello world!
HELLO WORLD!


In [52]:
name = 'my name'
print a + ' My name is ' + name

Hello world! My name is my name


In [53]:
print a*3

Hello world!Hello world!Hello world!


In [54]:
groceries = "milk,eggs,bacon,spinach,olive oil,cookies"
groceries.split(',')

['milk', 'eggs', 'bacon', 'spinach', 'olive oil', 'cookies']

In [55]:
groceries.split(',')[-1]

'cookies'

In [59]:
pretty_groceries = '\n- '.join(groceries.split(','))
#print pretty_groceries
#print '- '+ pretty_groceries
#pretty_groceries

#### Python tuples
Tuples are similar to lists, except that they are ***immutable***, meaning that they cannot be changed in place.  Tuples are indicated by parenthesis **`(`** and **`)`**.

In [60]:
x = (1, 'a', 2.5)

In [61]:
type(x)

tuple

In [62]:
x

(1, 'a', 2.5)

In [63]:
(1,)

(1,)

In [64]:
x[0]

1

In [65]:
x[0] = 'b'

TypeError: 'tuple' object does not support item assignment

#### Python sets

A python set is an unordered mutable collection of distinct elements - i.e. a list with duplicates removed.

In [66]:
y = set([1, 1, 2, 3, 5, 8])

In [67]:
y

{1, 2, 3, 5, 8}

A set can be used as a quick method to remove duplicate elements from a list:

In [68]:
a = [1, 3, 4, 5, 5, 5, 7, 8, 8, 9]

In [69]:
list(set(a))

[1, 3, 4, 5, 7, 8, 9]

#### Python dictionaries (i.e. associative arrays)

Dictionaries are ***unordered*** collections of ***key-value pairs***.  Dictionaries can use various types for keys (e.g. strings, ints) so long as the key is immutable.  Values are looked up by key.  In python dictionaries are indicated by ***curly braces { }***

In [70]:
info = {'name': 'Bob', 'age': 54, 'kids': ['Henry', 'Phil']}

In [71]:
info['name']

'Bob'

In [72]:
info['age'] = 55

In [73]:
info['age']

55

In [74]:
num_kids = len(info['kids'])

In [75]:
num_kids

2

Some additional references:

http://python.org/documentation/  
http://www.greenteapress.com/thinkpython/thinkpython.pdf  
http://nbviewer.ipython.org/url/www.astro.washington.edu/users/vanderplas/Astr599/notebooks/01_basic_training.ipynb  
http://nbviewer.ipython.org/url/www.astro.washington.edu/users/vanderplas/Astr599/notebooks/02_advanced_data_structures.ipynb

## Flow Control

Lists, tuples, sets,and dictionaries can be iterated through (and this will be very common). There are good and bad ways to iterate through lists.

In [76]:
# for loop to print 1 through 5
nums = range(1, 6)      # create a list of 1 through 5
for num in nums:        # num 'becomes' each list element for one loop
    print num

1
2
3
4
5


In [77]:
# for loop to print 1, 3, 5
other = [1, 3, 5]       # create a different list
for x in other:         # name 'x' does not matter
    print x             # this loop only executes 3 times (not 5)

1
3
5


In [78]:
# for loop to create a list of cubes of 1 through 5
cubes = []                  # create empty list to store results
for num in nums:            # loop through nums (will execute 5 times)
    cubes.append(num**3)    # append the cube of the current value of num
    
print cubes

[1, 8, 27, 64, 125]


In [79]:
# equivalent list comprehension
cubes = [num**3 for num in nums]
print cubes

[1, 8, 27, 64, 125]


### Python File Object

In [80]:
fh = open('../data/chipotle.tsv', 'r')

for line in fh:
    if 'Veggie Salad Bowl' in line:
        print line

83	1	Veggie Salad Bowl	[Fresh Tomato Salsa, [Fajita Vegetables, Rice, Black Beans, Cheese, Sour Cream, Guacamole, Lettuce]]	$11.25 

128	1	Veggie Salad Bowl	[Fresh Tomato Salsa, [Fajita Vegetables, Lettuce, Guacamole, Sour Cream, Cheese, Black Beans, Rice]]	$11.25 

195	1	Veggie Salad Bowl	[Fresh Tomato Salsa, [Fajita Vegetables, Rice, Black Beans, Cheese, Guacamole, Lettuce]]	$11.25 

207	1	Veggie Salad Bowl	[Fresh Tomato Salsa, [Rice, Lettuce, Guacamole, Fajita Vegetables, Cheese, Sour Cream, Black Beans]]	$11.25 

394	1	Veggie Salad Bowl	[Fresh Tomato Salsa, [Fajita Vegetables, Lettuce]]	$8.75 

536	1	Veggie Salad Bowl	[Fresh Tomato Salsa, [Fajita Vegetables, Rice, Black Beans, Cheese, Sour Cream]]	$8.75 

760	1	Veggie Salad Bowl	[Fresh Tomato Salsa, [Fajita Vegetables, Rice, Black Beans, Cheese, Guacamole, Lettuce]]	$11.25 

869	1	Veggie Salad Bowl	[Tomatillo Red Chili Salsa, [Fajita Vegetables, Rice, Black Beans, Cheese, Guacamole]]	$11.25 

896	1	Veggie Salad Bowl	[Roasted Chili 

In [81]:
with open('../data/chipotle.tsv', 'r') as fh:
    for line in fh:
        if 'Veggie Salad Bowl' in line:
            print line

83	1	Veggie Salad Bowl	[Fresh Tomato Salsa, [Fajita Vegetables, Rice, Black Beans, Cheese, Sour Cream, Guacamole, Lettuce]]	$11.25 

128	1	Veggie Salad Bowl	[Fresh Tomato Salsa, [Fajita Vegetables, Lettuce, Guacamole, Sour Cream, Cheese, Black Beans, Rice]]	$11.25 

195	1	Veggie Salad Bowl	[Fresh Tomato Salsa, [Fajita Vegetables, Rice, Black Beans, Cheese, Guacamole, Lettuce]]	$11.25 

207	1	Veggie Salad Bowl	[Fresh Tomato Salsa, [Rice, Lettuce, Guacamole, Fajita Vegetables, Cheese, Sour Cream, Black Beans]]	$11.25 

394	1	Veggie Salad Bowl	[Fresh Tomato Salsa, [Fajita Vegetables, Lettuce]]	$8.75 

536	1	Veggie Salad Bowl	[Fresh Tomato Salsa, [Fajita Vegetables, Rice, Black Beans, Cheese, Sour Cream]]	$8.75 

760	1	Veggie Salad Bowl	[Fresh Tomato Salsa, [Fajita Vegetables, Rice, Black Beans, Cheese, Guacamole, Lettuce]]	$11.25 

869	1	Veggie Salad Bowl	[Tomatillo Red Chili Salsa, [Fajita Vegetables, Rice, Black Beans, Cheese, Guacamole]]	$11.25 

896	1	Veggie Salad Bowl	[Roasted Chili 

### Python packages (brief intro)

Python has an extensive collection of third-party libraries, or ***packages***, with additional functions, data-structures, etc.  Many (most?) packages of interest are hosted on the Python Package Index ***pypi***, and can be installed into your environment using ***pip***.  The Anaconda distribution in the pre-work includes a number of these that are useful in data science, so you should have most of them installed already.  

ref:  https://pypi.python.org/pypi

To start, let's import a python package called numpy.

In [82]:
import numpy as np

A note on namespaces when importing - there are a few different ways to import:

    1. import numpy

    - all submodules of numpy are accessible in the numpy namespace
    - e.g. numpy.array([1,2,3])


    2. import numpy as np

    - same as 1 except an alias 'np' is created for the namespace instead
    - e.g. np.array([1,2,3])


    3. from numpy import *

    - adds all submodules to global namespace
    - e.g. array([1,2,3])
    - Note: This can be dangerous because if different modules have submodules with the same name than whatever is imported last will overrite what came before it - i.e. naming collision -> overwriting!.
    
    4. from numpy import array
    
    - will import only the indicated submodules into the global namespace
    - e.g. array([1,2,3])
    - Note: can be ok since you are being explicit
    
    We will generally use 2 and 4 (sparingly).

What does this package contain?  Introspect with `dir` to find out which names a module defines:

In [83]:
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'PackageLoader',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__name__',
 '__package__',
 '__path__',
 '__version__',
 '_import_tools',
 '_mat',
 'abs',
 'absolute',
 'absolute_import',
 'add',
 'add_docstring',
 'add_newdoc'

For detailed info about a particular name, use the ***help*** command:

In [84]:
help(np.array)

Help on built-in function array in module numpy.core.multiarray:

array(...)
    array(object, dtype=None, copy=True, order=None, subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an
        object whose __array__ method returns an array, or any
        (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then
        the type will be determined as the minimum type required
        to hold the objects in the sequence.  This argument can only
        be used to 'upcast' the array.  For downcasting, use the
        .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy
        will only be made if __array__ returns a copy, if obj is a
        nested sequence, or if a copy is needed to satisfy any of the other
        requirements (`dtype`, `order`, etc.).

In [85]:
data = np.array([[1, 2, 3],[2, 4, 9]])
data

array([[1, 2, 3],
       [2, 4, 9]])

In [86]:
data[0]  # first row

array([1, 2, 3])

In [87]:
data[ : , 1]  # all rows, second column

array([2, 4])

Because of the way numpy arrays are stored in memory, all elements have to be of the same type.  If there is just one float, all the values will be converted to a float.

In [88]:
data = np.array([[1, 2, 3],[2, 4.5, 9]])
data

array([[ 1. ,  2. ,  3. ],
       [ 2. ,  4.5,  9. ]])

Notice that the format of this data is different, something called a numpy `record array`.  

ref: http://docs.scipy.org/doc/numpy/user/basics.rec.html#structured-arrays

In [89]:
data[0]  # first row of data array

array([ 1.,  2.,  3.])

In [90]:
data[0][3]  # first row, fourth item in tuple

IndexError: index 3 is out of bounds for axis 0 with size 3

Plus there's more!
    
- list and array slicing
- python list comprehensions
- numpy array manipulation